'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CustomerUserManual

    '''<summary>
    '''ddlHelp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlHelp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DisputesPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DisputesPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''CreatingAccountPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreatingAccountPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ModifyingYourAccountPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ModifyingYourAccountPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''StocksPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StocksPanel As Global.System.Web.UI.WebControls.Panel
End Class
